# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_astgrepr_wrappers", use_symbols = TRUE, package_name = "astgrepr")

#' @docType package
#' @usage NULL
#' @useDynLib astgrepr, .registration = TRUE
NULL

SgRoot <- new.env(parent = emptyenv())

SgRoot$new <- function(src, lang) .Call(wrap__SgRoot__new, src, lang)

SgRoot$root <- function() .Call(wrap__SgRoot__root, self)

SgRoot$filename <- function() .Call(wrap__SgRoot__filename, self)

#' @export
`$.SgRoot` <- function (self, name) { func <- SgRoot[[name]]; environment(func) <- environment(); func }

#' @export
`[[.SgRoot` <- `$.SgRoot`

SgNode <- new.env(parent = emptyenv())

SgNode$range <- function() .Call(wrap__SgNode__range, self)

SgNode$is_leaf <- function() .Call(wrap__SgNode__is_leaf, self)

SgNode$is_named <- function() .Call(wrap__SgNode__is_named, self)

SgNode$is_named_leaf <- function() .Call(wrap__SgNode__is_named_leaf, self)

SgNode$kind <- function() .Call(wrap__SgNode__kind, self)

SgNode$text <- function() .Call(wrap__SgNode__text, self)

SgNode$matches <- function(rule) .Call(wrap__SgNode__matches, self, rule)

SgNode$get_match <- function(meta_var) .Call(wrap__SgNode__get_match, self, meta_var)

SgNode$get_transformed <- function(meta_var) .Call(wrap__SgNode__get_transformed, self, meta_var)

SgNode$get_root <- function() .Call(wrap__SgNode__get_root, self)

SgNode$find <- function(rule) .Call(wrap__SgNode__find, self, rule)

SgNode$field <- function(name) .Call(wrap__SgNode__field, self, name)

SgNode$parent <- function() .Call(wrap__SgNode__parent, self)

SgNode$child <- function(nth) .Call(wrap__SgNode__child, self, nth)

SgNode$next_ <- function() .Call(wrap__SgNode__next_, self)

SgNode$prev <- function() .Call(wrap__SgNode__prev, self)

#' @export
`$.SgNode` <- function (self, name) { func <- SgNode[[name]]; environment(func) <- environment(); func }

#' @export
`[[.SgNode` <- `$.SgNode`


# nolint end
